
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ContextApiProvider from "./store/contextApi";
import SignUpContextProvider from "./store/signUpContext";
import SignInContextProvider from "./store/signInContext";





const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <SignUpContextProvider>
        <SignInContextProvider>
          <ContextApiProvider>
            <body className={inter.className}>

              {children}

            </body>
          </ContextApiProvider>
        </SignInContextProvider>
      </SignUpContextProvider>

    </html>
  );
}
